### ISSUE TITLE
Confused on Source

### ISSUE THREAD

**Issue by FryGuyFlies** [D3vil-Design/Ender3-V3-KE-Hardware-Mods#1]
Hey Derrick, I don't mean to complain, but I've been getting confused as to why there is this page without the the rails explanation and then there is another one on your page.  I'm a bit of a noob at getting around here, so I keep coming back to this empty page expecting to find everything here.  I wonder if you could maybe post a link here to your other page, because I think some of your other posts, such as on Discord, link to this one.

**Comment by DerrickDarrell** [comment]
https://github.com/DerrickDarrell/Creality-Ender-3-V3-SE-KE

both gits are linked in the welcome page in the discord

**Comment by FryGuyFlies** [comment]
Thank you, could that be added to the ReadMe?

**Comment by FryGuyFlies** [comment]
Hmm, I can see it now.  I guess I'm just confused as to why this page exists at all when none of the mods are listed here.  Especially for KE owners like me, this seems like the central location.  Going by favourites, this page does seem to get more attention and for some reason your channel doesn't show up when I do a search to make new favourites.

I'm not trying to be critical or needy, just trying to make things more straightforward for any newcomers.
